data:
  source_path: "data/put_groceries_in_cupboard_episode1_start"
  assets_directory: "output"
  assets_path: "${data.source_path}/${data.assets_directory}"
  trajectory_file: "${data.source_path}/dictionary.pkl"

defaults:
  - simulation: coppelia_simulation
  - training: coppelia_params

