name: Build and Push Base Image

on:
  workflow_dispatch:  # for manual trigger

jobs:
  build-and-push-base:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build & push base image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --push \
            -f Dockerfile.base \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/drema-base:latest \
            .
