name: Build and Push Image

on:
  workflow_dispatch: # for manual trigger on github
  push:
    branches: [ "image-release" ]
    tags:
      - "v*"  # for triggering with versioning 
      - "build-*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build & push amd64 image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --push \
            --cache-from=type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/refact:cache \
            --cache-to=type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/refact:cache,mode=max \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --build-arg DOCKER_BUILDKIT=1 \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/refact:${{ github.ref_name }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/refact:latest \
            .
